---
# OPNsense Utility Scripts
# Non-monitoring scripts for OPNsense firewall management

- name: Deploy VPN country switcher script
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../../scripts/services/opnsense/switch_vpn_country.sh"
    dest: /usr/local/bin/switch-vpn-country.sh
    owner: root
    group: wheel
    mode: '0755'
  tags: [opnsense, vpn]
